#!/usr/bin/env python3
"""export_onnx.py — export a trained model to ONNX and write the
controller's schema-v1 model manifest next to it.

The manifest is the contract consumed by controller/src/manifest.rs
(validate with `controller.exe --manifest-check <manifest.json>`).
Labels order MUST match the class indices used in annotation; the
export fails loudly on any mismatch instead of guessing.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
import sys
import tempfile
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("weights", nargs="?", help="trained .pt weights (kept out of Git)")
    p.add_argument("--name", required=True, help="model name for the manifest")
    p.add_argument("--version", default="0.1.0", help="model version for the manifest")
    p.add_argument("--game-profile", default="generic-ui", help="game/profile tag (default: generic-ui)")
    p.add_argument("--labels", required=True,
                   help="comma-separated class names, index-ordered (e.g. 'button_green,dialog')")
    p.add_argument("--imgsz", type=int, default=640, help="export imgsz (default: 640)")
    p.add_argument("--confidence", type=float, default=0.6, help="default_confidence in (0,1] (default: 0.6)")
    p.add_argument("--opset", type=int, default=13, help="ONNX opset (default: 13)")
    p.add_argument("--out-dir", default="dist/models", help="export directory (default: dist/models)")
    p.add_argument("--yes", action="store_true", help="actually run (requires ultralytics)")
    p.add_argument("--selftest", action="store_true",
                   help="run the synthetic end-to-end check and exit")
    return p.parse_args()


def build_manifest(args: argparse.Namespace, onnx_name: str) -> dict:
    """The schema-v1 manifest contract consumed by controller/src/manifest.rs —
    kept as a function so the selftest can pin field-for-field without
    ultralytics (labels order MUST match annotation class indices)."""
    labels = [s.strip() for s in args.labels.split(",") if s.strip()]
    return {
        "schema_version": 1,
        "name": args.name,
        "version": args.version,
        "game_profile": args.game_profile,
        "input_size": {"width": args.imgsz, "height": args.imgsz},
        "labels": labels,
        "default_confidence": args.confidence,
        "weights": onnx_name,
        "notes": "Generated by tools/vision/export_onnx.py; weights stay external to Git.",
    }


def main() -> int:
    args = parse_args()
    labels = [s.strip() for s in args.labels.split(",") if s.strip()]
    if not labels:
        print("export_onnx: ERROR --labels must name at least one class", file=sys.stderr)
        return 2
    if not (0.0 < args.confidence <= 1.0):
        print("export_onnx: ERROR --confidence must be in (0, 1]", file=sys.stderr)
        return 2
    if not (0 < args.imgsz <= 4096):
        print("export_onnx: ERROR --imgsz must be in 1..=4096", file=sys.stderr)
        return 2
    weights = Path(args.weights) if args.weights else None
    if weights is None or not weights.is_file():
        print(f"export_onnx: ERROR weights not found: {weights}", file=sys.stderr)
        return 2

    out_dir = Path(args.out_dir)
    stem = weights.stem
    onnx_path = out_dir / f"{stem}.onnx"
    manifest_path = out_dir / f"{stem}.manifest.json"
    print("export_onnx: PLAN " + json.dumps({
        "weights": str(weights.resolve()),
        "onnx": str(onnx_path),
        "manifest": str(manifest_path),
        "imgsz": args.imgsz,
        "opset": args.opset,
        "labels": labels,
    }, indent=2))
    if not args.yes:
        print("export_onnx: dry plan only — pass --yes to execute")
        return 0

    if importlib.util.find_spec("ultralytics") is None:
        print("export_onnx: ERROR ultralytics is not installed; refusing to auto-install",
              file=sys.stderr)
        return 2

    from ultralytics import YOLO  # imported only after the gate

    model = YOLO(str(weights))
    exported = model.export(format="onnx", imgsz=args.imgsz, opset=args.opset)
    exported_path = Path(exported)
    out_dir.mkdir(parents=True, exist_ok=True)
    if exported_path != onnx_path:
        exported_path.replace(onnx_path)

    manifest = build_manifest(args, onnx_path.name)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"export_onnx: wrote {onnx_path}")
    print(f"export_onnx: wrote {manifest_path}")
    print("export_onnx: validate with: controller.exe --manifest-check "
          f"{manifest_path}")
    return 0


def selftest() -> int:
    """The no-ultralytics surface through the REAL CLI: guard refusals, the
    dry plan, and the manifest contract pinned field-for-field against
    controller/src/manifest.rs (schema_version strict 1, input_size ints,
    labels order, confidence in (0,1])."""
    ok = True

    def check(cond: bool, why: str) -> None:
        nonlocal ok
        if not cond:
            print(f"selftest FAIL: {why}")
            ok = False

    def run(*argv: str) -> subprocess.CompletedProcess:
        return subprocess.run([sys.executable, str(Path(__file__).resolve()), *argv],
                              capture_output=True, text=True)

    with tempfile.TemporaryDirectory(prefix="export-onnx-selftest-") as td:
        root = Path(td)
        weights = root / "demo.pt"
        weights.write_bytes(b"not really a model - the dry plan never reads it")

        base = [str(weights), "--name", "self", "--out-dir", str(root / "out")]
        proc = run(*base, "--labels", "a,b")
        check(proc.returncode == 0 and "dry plan only" in proc.stdout,
              f"dry plan exit {proc.returncode}: {proc.stderr[-200:]}")
        check('"labels"' in proc.stdout and '"opset"' in proc.stdout,
              "plan must name labels and opset")

        expect_fail_cases = [
            ("no-weights", ("--name", "x", "--labels", "a"), str(root / "missing.pt")),
            ("empty-labels", ("--name", "x", "--labels", ",,", str(weights)), None),
            ("confidence-zero", (*base, "--labels", "a", "--confidence", "0"), None),
            ("confidence-over", (*base, "--labels", "a", "--confidence", "1.5"), None),
            ("imgsz-zero", (*base, "--labels", "a", "--imgsz", "0"), None),
            ("imgsz-over", (*base, "--labels", "a", "--imgsz", "5000"), None),
        ]
        for why, argv, positional in expect_fail_cases:
            args = list(argv)
            if positional:
                args.insert(0, positional)
            proc = run(*args)
            check(proc.returncode == 2 and "ERROR" in proc.stderr and "Traceback" not in proc.stderr,
                  f"{why}: exit={proc.returncode} stderr={proc.stderr[-160:]}")

        # manifest contract, pinned without ultralytics: build_manifest is the
        # exact dict main() writes next to the exported onnx
        ns = argparse.Namespace(name="demo", version="0.2.0", game_profile="hsr-ui",
                                labels="button_green,dialog", imgsz=416,
                                confidence=0.55, opset=13)
        m = build_manifest(ns, "demo.onnx")
        check(m["schema_version"] == 1, "schema_version must be exactly 1")
        check(m["labels"] == ["button_green", "dialog"], "labels must keep index order")
        check(m["input_size"] == {"width": 416, "height": 416}, "input_size must mirror imgsz")
        check(m["default_confidence"] == 0.55 and 0.0 < m["default_confidence"] <= 1.0,
              "confidence out of contract range")
        check(m["weights"] == "demo.onnx", "weights must be the sibling onnx file name")
        # JSON round-trip must stay parseable and UTF-8 clean
        json.dumps(m, ensure_ascii=False)

    if ok:
        print("export_onnx selftest: PASS (dry plan, 6 guard refusals, manifest contract pinned)")
        return 0
    return 1


if __name__ == "__main__":
    # selftest flag shared with the other tools' convention
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    sys.exit(main())
